<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Currency conversion application</title>

</head>
<body>
  <div id="header" style="background-color: #EEEEEE; height: 30px; padding-left: 10px;">
    <div id="header-logo" style="float: left">
      <b>Currency Converter</b>
    </div>
  </div>
    
  <div class="main-content">
    <?php echo $this->layout()->content; ?>
  </div>

  <noscript id="deferred-styles">
    <link rel="stylesheet" href="css/style.css"/>
  </noscript>
  <script>
    var loadDeferredStyles = function() {
      var addStylesNode = document.getElementById("deferred-styles");
      var replacement = document.createElement("div");
      replacement.innerHTML = addStylesNode.textContent;
      document.body.appendChild(replacement)
      addStylesNode.parentElement.removeChild(addStylesNode);
    };
    var raf = requestAnimationFrame || mozRequestAnimationFrame ||
      webkitRequestAnimationFrame || msRequestAnimationFrame;
    if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
    else window.addEventListener('load', loadDeferredStyles);
  </script>
  <script defer type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
  <script defer type="text/javascript" src="js/script.js"></script>

</body>
</html>